# ndarray 对象

# 创建数组

In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b[1,1] = 10
print(a.shape)
print(b.shape)
print(a.dtype)
print(b)

(3,)
(3, 3)
int32
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]


# 结构数组

In [9]:
persontype = np.dtype({
    'names':['name','age','chinese','math','english'],
    'formats':['S32','i','i','i','f']})

peoples = np.array([('zhangfei',32,75,100,90),('guanyu',24,85,96,88.5),('zhaoyun',28,85,92,96.5)], dtype = persontype)
ages = peoples[:]['age']
chineses = peoples[:]['chinese']
maths = peoples[:]['math']
englishs = peoples[:]['english']

print(np.mean(ages))
print(np.mean(chineses))
print(np.amax(maths))
print(np.amin(englishs))

28.0
81.66666666666667
100
88.5


# ufunc 运算

# 连续数组的创建

In [15]:
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)

print(x1)
print(x2)

[1 3 5 7 9]
[1. 3. 5. 7. 9.]


# 算数运算

In [28]:
x1 = np.arange(1,11,2)
x2 = np.linspace(1,9,5)

print('x1: %a' %x1)
print(x2)

print(np.add(x1,x2))
print(np.subtract(x1,x2))
print(np.multiply(x1,x2))
print(np.divide(x1,x2))
print(np.power(x1,x2))
print(np.mod(x1,x2))

x1: array([1, 3, 5, 7, 9])
[1. 3. 5. 7. 9.]
[ 2.  6. 10. 14. 18.]
[0. 0. 0. 0. 0.]
[ 1.  9. 25. 49. 81.]
[1. 1. 1. 1. 1.]
[1.00000000e+00 2.70000000e+01 3.12500000e+03 8.23543000e+05
 3.87420489e+08]
[0. 0. 0. 0. 0.]


# 统计函数

# 最大最小值函数

In [33]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.amin(a))
print(np.amin(a,0))
print(np.amin(a,1))
print(np.amax(a))
print(np.amax(a,0))
print(np.amax(a,1))

1
[1 2 3]
[1 4 7]
9
[7 8 9]
[3 6 9]


# 统计最大最小值的差

In [34]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.ptp(a))
print(np.ptp(a,0))
print(np.ptp(a,1))

8
[6 6 6]
[2 2 2]


# 统计数组的百分位数

In [35]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.percentile(a,50))
print(np.percentile(a,50,axis=0))
print(np.percentile(a,50,axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


# 统计数组的中位数，平均数

In [37]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
#求中位数
print(np.median(a))
print(np.median(a,axis=0))
print(np.median(a,axis=1))
#求平均数
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
5.0
[4. 5. 6.]
[2. 5. 8.]


# 统计数组中的加权平均值

In [39]:
a = np.array([1,2,3,4])
wts = np.array([1,2,3,4])
print(np.average(a))
print(np.average(a,weights=wts))

2.5
3.0


# 统计数组中的标准差

In [40]:
a = np.array([1,2,3,4])
print(np.std(a))
print(np.var(a))

1.118033988749895
1.25


# NumPy排序

In [44]:
a = np.array([[4,3,2],[2,4,1]])
print(np.sort(a))
print()
print(np.sort(a,axis=None))
print()
print(np.sort(a,axis=0))
print()
print(np.sort(a,axis=1))

[[2 3 4]
 [1 2 4]]

[1 2 2 3 4 4]

[[2 3 1]
 [4 4 2]]

[[2 3 4]
 [1 2 4]]


# 统计全班的成绩

In [49]:
scoreType = ({
    'names':['name','chinese','math','english'],
    'formats':['S32','f','f','f']
})
scores = np.array([('zhangfei',66,65,30),('guanyu',95,85,98),('zhaoyun',93,92,96),('huangzhong',90,88,77),('weidian',80,90,90)],dtype=scoreType)
chinese = scores[:]['chinese']
math = scores[:]['math']
english = scores[:]['english']
print(np.amax(chinese))
print(np.amin(math))
print(np.mean(english))

print(np.std(chinese))
print(np.var(chinese))

95.0
65.0
78.2
10.72194
114.96001
